### ISSUE TITLE
UI for adding testcases

### ISSUE THREAD

**Issue by dub-basu** [CRUx-BPHC/crux-judge#20]
IMPORTANT : Make sure #19 has been resolved and closed before you start solving the current issue.

Testcases are currently saved manually. Enable creating and adding testcases from /admin panel(or bank app) while adding problems in problem bank using a UI. Save all testcases in `src/server/bank/testcases`. 
When a problem is added from problem bank to contest problems, make sure the corresponding testcases are copied to `src/server/contest/testcases/` as well.

**Comment by aero31aero** [comment]
Update: #19 has been closed. Can proceed forward with this.

**Comment by dub-basu** [comment]
Issue resolved
